const iceCreams = [
    {
    icecream: "Mint Chocolate",
    price: 6.00,
    calories: 200,
    id: 1,
    img: "/img/MintChoc_Ice_cream.png",
    alt: "Mint-Chocolate Ice-cream",
}, 
{
    icecream: "Chocolate",
    price: 7.00,
    calories: 250,
    id: 2,
    img: "/img/Chocolate_Ice_cream.png",
    alt: "Chocolate Ice-cream",
},
{
    icecream: "Cookie Dough",
    price: 7.00,
    calories: 280,
    id: 3,
    img: "/img/CookieDough_Ice_cream.png",
    alt: "Cookie-Dough Ice-cream",
},
{
    icecream: "Strawberry",
    price: 6.00,
    calories: 125,
    id: 4,
    img: "/img/Strawberry_Ice_cream.png",
    alt: "Strawberry Ice-cream",
},
{
    icecream: "Cherry",
    price: 6.00,
    calories: 140,
    id: 5,
    img: "/img/Cherry_Ice_cream.png",
    alt: "Cherry Ice-cream",
},
{
    icecream: "Vanilla",
    price: 5.00,
    calories: 130,
    id: 6,
    img: "/img/Vanilla_Ice_cream.png",
    alt: "Vanilla Ice-cream",
}
];

const teas = [
{
    tea: "Black",
    price: 1.00,
    calories: 4,
    id: 7,
    img: "/img/Black_Tea_Final.png",
    alt: "Black Tea",
},
{
    tea: "Green",
    price: 1.50,
    calories: 3,
    id: 8,
    img: "/img/Green_Tea_Final.png",
    alt: "Green Tea",
},
{
    tea: "Peppermint",
    price: 1.50,
    calories: 2,
    id: 9,
    img: "/img/Peppermint_Tea_Final.png",
    alt: "Peppermint Tea",
},
{
    tea: "Hibiscus",
    price: 2.00,
    calories: 35,
    id: 10,
    img: "/img/Hibiscus_Tea_Final.png",
    alt: "Hibiscus Tea",
},
{
    tea: "Ginger",
    price: 2.00,
    calories: 2,
    id: 11,
    img: "/img/Ginger_Tea_Final.png",
    alt: "Ginger Tea",
},
{
    tea: "Jasmine",
    price: 2.00,
    calories: 5,
    id: 12,
    img: "/img/Jasmine_Tea_Final.png",
    alt: "Jasmine Tea",
},
];