"use strict";

/* Start Page Overlay */

const startpageButton = document.querySelector("#start_button");
const icecreamButton = document.querySelector(".ice-cream-card");
const icecreamModal = document.getElementById("ice-cream-modal");

// Event Listener to change display on parent container to none once button clicked

startpageButton.addEventListener("click", (e) => {
  const target = e.target.closest(".showcase_overlay");
  console.log(target);

  target.style.display = "none";

  //Timer to race against promise fulfillment generated by retrieving localStorage for favourite meals.
});

icecreamButton.addEventListener("click", () => {
  icecreamModal.showModal();
});
