"use strict";

/* Start Page Overlay */

const startpageButton = document.querySelector("#start_button");
const icecreamButton = document.querySelector(".ice-cream-card");
const teaButton = document.querySelector(".tea-card")
const shoppingBasket = document.querySelector(".shopping-basket")
const productModal = document.getElementById("product-modal");
const productModal2 = document.getElementById("product-modal2");
const productModal3 = document.getElementById("product-modal3");
const mainContainer = document.querySelector('.main-container');
const closeModalXButtons = document.querySelectorAll('.close-icon-x');

// Event Listener to change display on parent container to none once button clicked

startpageButton.addEventListener("click", (e) => {
  const target = e.target.closest(".showcase_overlay");
  console.log(target);

  target.style.display = "none";

  //Timer to race against promise fulfillment generated by retrieving localStorage for favourite meals.
});

icecreamButton.addEventListener("click", (e) => {
  mainContainer.style.display = "none";



  productModal.classList.add("dialog-scale")
});

teaButton.addEventListener("click", (e) => {
  mainContainer.style.display = "none";
  console.log(teaButton);

  productModal2.classList.add("dialog-scale")
});

shoppingBasket.addEventListener("click", (e) => {
  mainContainer.style.display = "none";
  console.log(shoppingBasket);

  productModal3.classList.add("dialog-scale")
});

// Event Listener for X Button in Modal for Products

closeModalXButtons.forEach(function(btn) { btn.addEventListener("click", (e) => {
  console.log("button clicked")
  mainContainer.style.display = "block";

  const modal = e.target.closest('[data-modal]')
  console.log(modal)

  modal.classList.remove("dialog-scale")
})});